<option value="default">Please Select</option>
<option value="1">Accountancy/Finance</option>
<option value="2">Administration</option>
<option value="3">Agriculture &amp; Forestry &amp; Fishing</option>
<option value="4">Architecture/Interior Design</option>
<option value="5">Arts &amp; Entertainment</option>
<option value="6">Automotive &amp; Motor Vehicle</option>
<option value="7">Apparel/Clothing</option>
<option value="8">Banking &amp; Financial Services</option>
<option value="9">Broadcasting</option>
<option value="10">Beauty &amp; Cosmetics</option>
<option value="11">Fashion &amp; Designing</option>
<option value="12">Catering services &amp; Hospitality</option>
<option value="13">Construction/Cement/Metals</option>
<option value="14">Call Centre/Sales Services</option>
<option value="15">Design &amp; Creative</option>
<option value="16">Distribution &amp; Logistics</option>
<option value="17">Education, Training &amp; Library</option>
<option value="18">Electronics</option>
<option value="19">Energy</option>
<option value="20">Engineering</option>
<option value="21">Event Management</option>
<option value="22">Government and Policy</option>
<option value="23">Health Services &amp; Pharmacy</option>
<option value="24">HR &amp; Recruiting</option>
<option value="25">Infrastructure</option>
<option value="26">Insurance</option>
<option value="27">IT Software &amp; Web Development</option>
<option value="28">IT-Hardware/Computer Networking</option>
<option value="29">Legal Affairs</option>
<option value="30">Manufacturing &amp; production</option>
<option value="31">Management &amp; Consultancy</option>
<option value="32">Marketing &amp; Advertisement</option>
<option value="33">Media, Communication &amp; News</option>
<option value="34">NGO &amp; Social Services</option>
<option value="35">Printing &amp; Publications</option>
<option value="36">Public Relations</option>
<option value="37">Customer Support /BPO </option>
<option value="38">Travel, Transportation &amp; Tourism</option>
<option value="39">Purchase/Logistics/Supply Chain</option>
<option value="40">Business Development</option>
<option value="41">Sales/Telemarketing</option>
<option value="42">Services</option>
<option value="43">Basic Computer Skill</option>
<option value="44">IT Solutions</option>
<option value="45">Warehousing</option>
<option value="46">Animation/Graphics/Web Designing </option>
<option value="47">System Engineering</option>
<option value="48">Writer</option>
<option value="49">Researcher</option>
<option value="50">Project Management</option>
<option value="51">Other</option>